### ISSUE TITLE
Doxygen Notations

### ISSUE THREAD

**Issue by imsarahkhan** [imsarahkhan/Group_3_Travel-Agency-Management-System#26]
Need to recheck all Doxygen comments and coding conventions to create a Doxygen HTML file.

**Comment by ramyathammineni** [comment]
Reviewed all the documentation and looks good

**Comment by kavyaram15** [comment]
I have made few changes and now everything looks good

**Comment by imsarahkhan** [comment]
Added Doxygen Documnetation
