### ISSUE TITLE
WIKI Documentation

### ISSUE THREAD

**Issue by imsarahkhan** [imsarahkhan/Group_3_Travel-Agency-Management-System#29]
Need to finalise Wiki Documentation

**Comment by ramyathammineni** [comment]
Please check all the hyperlinks are working fine or not

**Comment by kavyaram15** [comment]
Please add the Doxygen documentation

**Comment by kavyaram15** [comment]
I have made few changes to the coding conventions

**Comment by imsarahkhan** [comment]
Everything looks completed
